# Generated by Django 5.0.1 on 2024-03-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('OutOfStock', 'Нет в наличии'), ('InStock', 'Есть в наличии'), ('Soon', 'Скоро')], default='Soon', max_length=20),
        ),
    ]
