from django.db import migrations

def update_availability_values(apps, schema_editor):
    Product = apps.get_model('ecommerce', 'Product')
    # Обновление значений
    Product.objects.filter(availability='0').update(availability='OutOfStock')
    Product.objects.filter(availability='1').update(availability='InStock')
    Product.objects.filter(availability='2').update(availability='Soon')

class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_product_availability'),
    ]

    operations = [
        migrations.RunPython(update_availability_values),
    ]
# Generated by Django 5.0.1 on 2024-03-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_product_availability'),
    ]

    operations = [
    ]
