# Generated by Django 5.0.4 on 2024-04-16 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
        ('ecommerce', '0004_alter_order_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, limit_choices_to={'user': models.F('user')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.address'),
        ),
    ]
