# Generated by Django 5.0.4 on 2024-04-16 19:00

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_alter_order_created_at_alter_order_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='UZ'),
        ),
    ]
